version: '3'

services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    command: mongod --bind_ip 0.0.0.0 --smallfiles

  server:
    container_name: interview_api
    restart: on-failure
    image: node:8
    build:
      context: ../../
      dockerfile: ./Dockerfile
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    networks:
      - default
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.enable=true'
      - 'traefik.domain=api.winnersnevers.top'
      - 'traefik.basic.frontend.rule=Host:api.winnersnevers.top'
      - 'traefik.basic.port=3000'
      - 'traefik.basic.protocol=http'
