name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install
      run: |
        set -o pipefail
        npm install

    - name: lint
      run: npm run lint

    - name: build
      run: npm run build

    - name: test
      run: |
        cp support/.env.example .env
        docker-compose -f ./support/docker/docker-compose.test.yml up -d --build
        npm run test
        npm i -g codecov
        codecov -f coverage/*.json
